export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: 'Premium Ceramic Wall Tiles - Glossy White',
    slug: 'premium-ceramic-wall-tiles-glossy-white',
    description:
      'High-quality ceramic tiles perfect for modern bathrooms and kitchens. Features a glossy finish with excellent durability.',
    price: 1250,
    mrp: 1800,
    categoryPath: 'Construction > Tiles > Wall Tiles',
    categoryId: 1,
    vendorId: 2,
    images: ['/products/tile-1.jpg', '/products/tile-2.jpg'],
    attributes: {
      size: '600mm x 600mm',
      thickness: '10mm',
      finish: 'Glossy',
      material: 'Ceramic',
      application: ['Wall']
    },
    attributeStatus: 'complete',
    inStock: true,
    stockQuantity: 500,
    isActive: true,
    isHidden: false,
    isFlagged: false,
    createdAt: '2025-01-15T10:30:00Z',
    updatedAt: '2025-01-15T10:30:00Z',
  },
  {
    id: 2,
    name: 'Royal Emulsion Paint - Sky Blue',
    slug: 'royal-emulsion-paint-sky-blue',
    description:
      'Premium quality emulsion paint with superior coverage and long-lasting finish. Ideal for interior walls.',
    price: 3200,
    mrp: 4000,
    categoryPath: 'Finishes > Paints > Emulsion',
    categoryId: 2,
    vendorId: 3,
    images: ['/products/paint-1.jpg'],
    attributes: {
      coverage: '120 sq ft per liter',
      finish: 'Matte', // Corrected to match schema option
      volume: '20L', // Corrected to match schema option "20L" instead of "20 liters"
      surfaces: ['Interior Wall']
    },
    attributeStatus: 'complete',
    inStock: true,
    stockQuantity: 150,
    isActive: true,
    isHidden: false,
    isFlagged: false,
    createdAt: '2025-01-14T09:20:00Z',
    updatedAt: '2025-01-14T09:20:00Z',
  },
  {
    id: 3,
    name: 'Engineered Wood Flooring - Oak Natural',
    slug: 'engineered-wood-flooring-oak-natural',
    description:
      'Premium engineered wood flooring with natural oak finish. Easy installation and maintenance.',
    price: 8500,
    mrp: 10500,
    categoryPath: 'Flooring > Wood > Engineered Wood',
    categoryId: 3,
    vendorId: 4,
    images: ['/products/flooring-1.jpg'],
    attributes: {
      size: '1200mm x 190mm', // Note: 'size' isn't in my schema for Flooring, but 'thickness' is. I should be careful.
      // Schema for Flooring: material, finish, thickness, installation
      thickness: '15mm',
      finish: 'Oiled', // Corrected to match schema options
      material: 'Engineered Wood',
    },
    attributeStatus: 'complete',
    inStock: true,
    stockQuantity: 75,
    isActive: true,
    isHidden: false,
    isFlagged: false,
    createdAt: '2025-01-13T14:45:00Z',
    updatedAt: '2025-01-13T14:45:00Z',
  },
  {
    id: 4,
    name: "Classic Wooden Dining Table",
    slug: "classic-wooden-dining-table",
    description: "A beautiful 6-seater dining table made from solid teak wood.",
    price: 15000,
    mrp: 20000,
    categoryPath: "Furniture > Tables and chairs > Dining tables",
    categoryId: 4,
    vendorId: 2,
    images: [],
    attributes: {
      // Deliberately incomplete for testing
      material: "Solid Wood"
    },
    attributeStatus: "incomplete",
    inStock: true,
    stockQuantity: 5,
    isActive: true,
    isHidden: false,
    isFlagged: false,
    createdAt: '2025-01-16T10:00:00Z',
    updatedAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 101,
    name: 'Modern 3-Seater Sofa - Grey',
    slug: 'modern-3-seater-sofa-grey',
    description: 'Contemporary minimalist sofa with high-density foam cushioning.',
    price: 35000,
    mrp: 42000,
    categoryPath: 'Furniture > Sofas and armchairs > Sofas',
    categoryId: 6,
    vendorId: 2,
    images: [],
    attributes: {
      color: "Grey"
    },
    attributeStatus: 'incomplete',
    inStock: true,
    stockQuantity: 5,
    isActive: true,
    isHidden: false,
    isFlagged: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 102,
    name: 'Interior Wall Primer',
    slug: 'interior-wall-primer',
    description: 'Base coat for better paint adhesion and durability.',
    price: 1200,
    mrp: 1500,
    categoryPath: 'Finishes > Paints > Emulsion',
    categoryId: 2,
    vendorId: 2,
    images: [],
    attributes: {
      volume: "4L"
    },
    attributeStatus: 'incomplete',
    inStock: true,
    stockQuantity: 200,
    isActive: true,
    isHidden: false,
    isFlagged: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 103,
    name: 'Industrial Oak Dining Table',
    slug: 'industrial-oak-dining-table',
    description: 'Robust industrial style dining table with metal legs and solid oak top.',
    price: 28000,
    mrp: 35000,
    categoryPath: 'Furniture > Tables and chairs > Dining tables',
    categoryId: 6,
    vendorId: 2,
    images: [],
    attributes: {
      material: "Solid Wood",
      shape: "Rectangular"
      // Missing: seating_capacity (required)
    },
    attributeStatus: 'incomplete',
    inStock: true,
    stockQuantity: 8,
    isActive: true,
    isHidden: false,
    isFlagged: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 104,
    name: 'Herringbone Oak Flooring',
    slug: 'herringbone-oak-flooring',
    description: 'Classic herringbone pattern engineered wood flooring.',
    price: 4500,
    mrp: 5200,
    categoryPath: 'Flooring > Wood > Engineered Wood',
    categoryId: 3,
    vendorId: 2,
    images: [],
    attributes: {
      thickness: "14mm",
      finish: "Lacquered"
      // Missing: material (required)
    },
    attributeStatus: 'incomplete',
    inStock: true,
    stockQuantity: 120,
    isActive: true,
    isHidden: false,
    isFlagged: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 105,
    name: 'Carrara Marble Wall Tile',
    slug: 'carrara-marble-wall-tile',
    description: 'Elegant white marble tiles with grey veining.',
    price: 180,
    mrp: 220,
    categoryPath: 'Construction > Tiles > Wall Tiles',
    categoryId: 1,
    vendorId: 2,
    images: [],
    attributes: {
      size: "300x300mm",
      material: "Marble"
      // Missing: finish, application (required)
    },
    attributeStatus: 'incomplete',
    inStock: true,
    stockQuantity: 500,
    isActive: true,
    isHidden: false,
    isFlagged: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }


];