export const VENDORS = [
  {
    id: 1,
    name: 'Johnson Bathware',
    slug: 'johnson-bathware',
    logo: '/brands/johnson-bathware.svg',
    description: 'Premium bathroom solutions',
    rating: 4.8,
    totalProducts: 150,
  },
  {
    id: 2,
    name: 'Kajaria Ceramics',
    slug: 'kajaria-ceramics',
    logo: '/brands/kajaria.svg',
    description: "India's No. 1 Tile Company",
    rating: 4.7,
    totalProducts: 320,
  },
  {
    id: 3,
    name: 'Asian Paints',
    slug: 'asian-paints',
    logo: '/brands/asian-paints.svg',
    description: 'Beautiful Homes',
    rating: 4.9,
    totalProducts: 200,
  },
  {
    id: 4,
    name: 'Hafele',
    slug: 'hafele',
    logo: '/brands/hafele.svg',
    description: 'Furniture & Architectural Hardware',
    rating: 4.6,
    totalProducts: 180,
  },
];